name: mainstreet
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  flutter_native_splash: ^2.2.19
  firebase_storage: ^11.7.4
  firebase_crashlytics: ^3.5.4
  firebase_analytics: ^10.10.4
  firebase_messaging: ^14.9.1
  provider: ^6.1.2
  dio: ^5.4.3+1
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  package_rename: ^1.3.3
  path_to_regexp: ^0.4.0
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  rounded_loading_button_plus: ^3.0.1

package_rename_config:
  android:
    app_name: MainStreet
    package_name: dev.shivanshsingh.mainstreet_app
    override_old_package: dev.shivanshsingh.mainstreet
    lang: kotlin

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/main_street_icon.png

flutter_icons:
  image_path: "assets/images/main_street_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#00000000"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/onboarding/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 100
